/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "API key": {                                     "en": "API key",                                         "de": "API-Schlüssel",                                   "ru": "Ключ API",                                        "pt": "Chave API",                                       "nl": "API sleutel",                                     "fr": "Clé API",                                         "it": "Chiave API",                                      "es": "Clave API",                                       "pl": "Klucz API",                                       "zh-cn": "API 密钥"},
    "Get your key here": {                           "en": "Get your key here <a href=\"https://home.openweathermap.org/api_keys\">OpenWeatherMap</a>", "de": "Holen Sie sich Ihren Schlüssel hier <a href=\"https://home.openweathermap.org/api_keys\">OpenWeatherMap</a>", "ru": "Получите ваш ключ здесь <a href=\"https://home.openweathermap.org/api_keys\">OpenWeatherMap</a>", "pt": "Obtenha sua chave aqui <a href=\"https://home.openweathermap.org/api_keys\">OpenWeatherMap</a>", "nl": "Haal hier uw sleutel <a href=\"https://home.openweathermap.org/api_keys\">OpenWeatherMap</a>", "fr": "Obtenez votre clé ici <a href=\"https://home.openweathermap.org/api_keys\">OpenWeatherMap</a>", "it": "Ottieni la tua chiave qui <a href=\"https://home.openweathermap.org/api_keys\">OpenWeatherMap</a>", "es": "Obtenga su clave aquí <a href=\"https://home.openweathermap.org/api_keys\">OpenWeatherMap</a>", "pl": "Uzyskaj klucz tutaj <a href=\"https://home.openweathermap.org/api_keys\">OpenWeatherMap</a>", "zh-cn": "在此处获取您的钥匙 <a href=\"https://home.openweathermap.org/api_keys\">OpenWeatherMap</a>"},
    "Language": {                                    "en": "Language",                                        "de": "Sprache",                                         "ru": "Язык",                                            "pt": "Língua",                                          "nl": "Taal",                                            "fr": "La langue",                                       "it": "linguaggio",                                      "es": "Idioma",                                          "pl": "Język",                                           "zh-cn": "语言"},
    "Place": {                                       "en": "Place",                                           "de": "Ort",                                             "ru": "Место",                                           "pt": "Lugar, colocar",                                  "nl": "Plaats",                                          "fr": "Endroit",                                         "it": "Posto",                                           "es": "Lugar",                                           "pl": "Miejsce",                                         "zh-cn": "地方"},
    "Send missing translations to iobroker.net": {   "en": "Send missing translations to iobroker.net",       "de": "Senden Sie fehlende Übersetzungen an iobroker.net", "ru": "Отправить недостающие переводы на iobroker.net",  "pt": "Envie traduções faltando para iobroker.net",      "nl": "Verzend ontbrekende vertalingen naar iobroker.net", "fr": "Envoyer des traductions manquantes à iobroker.net", "it": "Invia traduzioni mancanti a iobroker.net",        "es": "Envía traducciones faltantes a iobroker.net",     "pl": "Wyślij brakujące tłumaczenia do iobroker.net",    "zh-cn": "将缺失的翻译发送到 iobroker.net"},
    "Use english metric system": {                   "en": "Use imperial system(°F, miles)",                  "de": "Verwenden Sie das Imperial-System (°F, Meilen)",  "ru": "Используйте английскую метрическую систему (°F, мили)", "pt": "Use o sistema métrico inglês (°F, milhas)",       "nl": "Gebruik het Engelse metrische systeem (°F, mijl)", "fr": "Utiliser le système métrique anglais (°F, miles)", "it": "Usa il sistema metrico inglese (°F, miglia)",     "es": "Utilice el sistema métrico inglés (°F, millas)",  "pl": "Użyj angielskiego systemu metrycznego (°F, mile)", "zh-cn": "使用英制（°F，英里）"},
};